name: Update COVID-19 Predictions

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-predictions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: covid-data
    
    - uses: actions/checkout@v2
      with:
        repository: hiytat/hiyata.github.io
        path: github-pages
        token: ${{ secrets.PAT }}  # Personal Access Token with repo scope
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r covid-data/requirements.txt
    
    - name: Debug - Print Python script content
      run: |
        echo "Content of covid_prediction.py:"
        cat covid-data/covid_prediction.py
    
    - name: Run prediction script
      run: |
        cd covid-data
        python -u covid_prediction.py
        echo "Current directory contents:"
        ls -la
        echo "Parent directory contents:"
        ls -la ..
        mkdir -p ../github-pages/assets/data
        if [ -f covid_predictions.json ]; then
          cp covid_predictions.json ../github-pages/assets/data/
          echo "File copied successfully"
        else
          echo "covid_predictions.json not found"
          exit 1
        fi
        echo "Contents of github-pages/assets/data directory:"
        ls -la ../github-pages/assets/data
    
    - name: Commit and push to github.io repository
      run: |
        cd github-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add assets/data/covid_predictions.json || echo "No changes to commit"
        git commit -m "Update COVID-19 predictions" || echo "No changes to commit"
        git push || echo "No changes to push"