name: Update COVID-19 Predictions

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch: 

jobs:
  update-predictions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout COVID-19 predictor repo
      uses: actions/checkout@v2
      with:
        repository: hiyata/covid-19-predictor
        path: covid-predictor
        token: ${{ secrets.PAT }}

    - name: Checkout hiyata.github.io repo
      uses: actions/checkout@v2
      with:
        repository: hiyata/hiyata.github.io
        path: hiyata.github.io
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r covid-predictor/requirements.txt

    - name: Run prediction script
      run: |
        cd covid-predictor
        python -u covid_prediction.py
        echo "Current directory contents:"
        ls -la
        cd ..
        echo "Root directory contents:"
        ls -la

    - name: Copy JSON files to github.io repo
      run: |
        mkdir -p hiyata.github.io/assets/covid-19-files
        if [ -f covid-predictor/covid_predictions.json ]; then
          cp covid-predictor/covid_predictions.json hiyata.github.io/assets/covid-19-files/
          echo "covid_predictions.json copied successfully"
        else
          echo "covid_predictions.json not found, creating an empty file"
          echo '{"dates":[],"lstm_predicted":[],"arima_predicted":[],"last_updated":""}' > hiyata.github.io/assets/covid-19-files/covid_predictions.json
        fi
        echo "Contents of hiyata.github.io/assets/covid-19-files directory:"
        ls -la hiyata.github.io/assets/covid-19-files

    - name: Commit and push to github.io repository
      run: |
        cd hiyata.github.io
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add assets/covid-19-files/covid_predictions.json
        git commit -m "Update COVID-19 predictions" || echo "No changes to commit"
        git push || echo "No changes to push"